#ifndef CPP_TEMPLATES_CHAPTER21_TEMPLATES_AND_INHERITANCE
#define CPP_TEMPLATES_CHAPTER21_TEMPLATES_AND_INHERITANCE

#include <type_traits>



#endif // !CPP_TEMPLATES_CHAPTER21_TEMPLATES_AND_INHERITANCE
