#ifndef CPP_TEMPLATES_CHAPTER_COMPILE_TIME_PROGRAMMING
#define CPP_TEMPLATES_CHAPTER_COMPILE_TIME_PROGRAMMING

#include <iostream>
#include <type_traits>

#endif // !CPP_TEMPLATES_CHAPTER_COMPILE_TIME_PROGRAMMING
